apiVersion: v1
kind: Namespace
metadata:
  name: guaycampo-staging
  labels:
    app.kubernetes.io/name: guaycampo
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: guaycampo-production
  labels:
    app.kubernetes.io/name: guaycampo
    environment: production
