apiVersion: v1
kind: Service
metadata:
  name: guaycampo-shifts
  labels:
    app: guaycampo-shifts
    app.kubernetes.io/name: guaycampo-shifts
    app.kubernetes.io/component: service
spec:
  selector:
    app: guaycampo-shifts
  ports:
    - name: http
      port: 3002
      targetPort: 3002
      protocol: TCP
    - name: ws
      port: 3002
      targetPort: 3002
      protocol: TCP
  type: ClusterIP
